version: '2'
services:
    chargeplanapplication-app:
        image: chargeplanapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://chargeplanapplication-mysql:3306/chargeplanapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://chargeplanapplication-elasticsearch:9200
        ports:
            - 9090:9090
    chargeplanapplication-mysql:
        extends:
            file: mysql.yml
            service: chargeplanapplication-mysql
    chargeplanapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: chargeplanapplication-elasticsearch
